### PR TITLE
SLING-8838 - Add HEAD support to ContentDispositionFilter

### PR DESCRIPTION
**Pull request by yesil**

### CODE REVIEW

**Comment by rombert** [comment]
@yesil  - it seems SonarCloud complains about the way you initialise the supported methods set - https://sonarcloud.io/project/issues?id=apache_sling-org-apache-sling-security&open=AW-f0hzpmTF_JQrYQPXS&pullRequest=1&resolved=false&types=BUG . Can you please update the code to use something else?

**Comment by rombert** [comment]
@yesil - I would like to make a release of the Security bundle today. Do you want to update the PR so that it is included in the next release?

**Comment by yesil** [comment]
@rombert I just updated my PR based on Sonar's recommendations.

**Comment by rombert** [comment]
@yesil  - could I also ask you to squash your commits? I can't squash + rebase from the GitHub UI ... Otherwise the PR is ready to merge

**Comment by kwin** [comment]
@rombert Squash and merge should work. At least for me it is provided as an option in the GitHub UI!

**Comment by rombert** [comment]
@kwin - Right, but squash and rebase is what we are looking for

**Comment by yesil** [comment]
@rombert  should I squash my commits on my local and push force?

**Comment by rombert** [comment]
@yesil  - yes, please

**Comment by rombert** [comment]
Applied, thanks @yesil for seeing this through

**Pull request merged**
